[env:waveshare-esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    lovyan03/LovyanGFX @ ^1.1.16
    bblanchon/ArduinoJson @ ^6.21.5
